global:
  scrape_interval: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts/alerts.yml
  - /etc/prometheus/rules/service_health_rules.yml

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['10.10.21.5:9100']
        labels:
          server: live
          host: ccdl-live-server-1
      - targets: ['10.10.21.6:9100']
        labels:
          server: backup
          host: ccdl-backup-server
      - targets: ['10.10.21.11:9100']
        labels:
          server: observatory
          host: ccdl-observatory-server

  - job_name: 'patroni_odoo'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.10.21.5:8008']
        labels:
          server: live
          host: ccdl-live-server-1
      - targets: ['10.10.21.6:8008']
        labels:
          server: backup
          host: ccdl-backup-server

  - job_name: 'nginx'
    static_configs:
      - targets: ['10.10.21.5:9113']
        labels:
          server: live
          host: ccdl-live-server-1
      - targets: ['10.10.21.6:9113']
        labels:
          server: backup
          host: ccdl-backup-server

  - job_name: 'postgres_odoo'
    static_configs:
      - targets: ['postgres-exporter-odoo-live:9191']
        labels:
          instance: 10.10.21.5:5432
          server: live
          host: ccdl-live-server-1
      - targets: ['postgres-exporter-odoo-backup:9192']
        labels:
          instance: 10.10.21.6:5432
          server: backup
          host: ccdl-backup-server
